#
#person:
#  lastName: zhangsan
#age: 18
#           boss: false
#           birth: 2017/2/12
#           maps: {k1: v1,k2: 12}
#           lists:
#             - lisi
#             - zhaoliu
#           dog:
#             name: xiaogou
#             age: 2